[build]
command = "npm run build"  # Comando para construir tu aplicaci칩n React
functions = "crud/functions"  # Directorio donde est치n las funciones serverless
publish = "build"  # Directorio donde est치 el build de tu aplicaci칩n React

[dev]
command = "npm start"  # Comando para iniciar el entorno de desarrollo local
functions = "crud/functions"  # Directorio de funciones para entorno de desarrollo
